---
title: "exploratory lda"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(lda)
library(readr)

```

```{r, transgender}
transgender_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_transgender_posts.csv")

transgender_corpus <- lexicalize(transgender_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
transgender_result <- lda.collapsed.gibbs.sampler(transgender_corpus$documents, K, transgender_corpus$vocab, 25, 0.1, 0.1)

transgender_top_words <- top.topic.words(transgender_result$topics, 10, by.score=TRUE)
```

```{r, asktransgender}
asktransgender_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_asktransgender_posts.csv")

asktransgender_corpus <- lexicalize(asktransgender_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
asktransgender_result <- lda.collapsed.gibbs.sampler(asktransgender_corpus$documents, K, asktransgender_corpus$vocab, 25, 0.1, 0.1)

asktransgender_top_words <- top.topic.words(asktransgender_result$topics, 10, by.score=TRUE)
```

```{r, genderqueer}
genderqueer_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_genderqueer_posts.csv")

genderqueer_corpus <- lexicalize(genderqueer_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
genderqueer_result <- lda.collapsed.gibbs.sampler(genderqueer_corpus$documents, K, genderqueer_corpus$vocab, 25, 0.1, 0.1)

genderqueer_top_words <- top.topic.words(genderqueer_result$topics, 10, by.score=TRUE)
```

```{r, NonBinary}
NonBinary_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_NonBinary_posts.csv")

NonBinary_corpus <- lexicalize(NonBinary_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
NonBinary_result <- lda.collapsed.gibbs.sampler(NonBinary_corpus$documents, K, NonBinary_corpus$vocab, 25, 0.1, 0.1)

NonBinary_top_words <- top.topic.words(NonBinary_result$topics, 10, by.score=TRUE)
```

```{r, transpassing}
transpassing_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_transpassing_posts.csv")

transpassing_corpus <- lexicalize(transpassing_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
transpassing_result <- lda.collapsed.gibbs.sampler(transpassing_corpus$documents, K, transpassing_corpus$vocab, 25, 0.1, 0.1)

transpassing_top_words <- top.topic.words(transpassing_result$topics, 10, by.score=TRUE)
```

```{r, FTMFitness}
FTMFitness_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_FTMFitness_posts.csv")

FTMFitness_corpus <- lexicalize(FTMFitness_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
FTMFitness_result <- lda.collapsed.gibbs.sampler(FTMFitness_corpus$documents, K, FTMFitness_corpus$vocab, 25, 0.1, 0.1)

FTMFitness_top_words <- top.topic.words(FTMFitness_result$topics, 10, by.score=TRUE)
```

```{r, EatingDisorders}
EatingDisorders_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_EatingDisorders_posts.csv")

EatingDisorders_corpus <- lexicalize(EatingDisorders_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
EatingDisorders_result <- lda.collapsed.gibbs.sampler(EatingDisorders_corpus$documents, K, EatingDisorders_corpus$vocab, 25, 0.1, 0.1)

EatingDisorders_top_words <- top.topic.words(EatingDisorders_result$topics, 10, by.score=TRUE)
```

```{r, EDAnonymous}
EDAnonymous_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_EDAnonymous_posts.csv")

EDAnonymous_corpus <- lexicalize(EDAnonymous_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
EDAnonymous_result <- lda.collapsed.gibbs.sampler(EDAnonymous_corpus$documents, K, EDAnonymous_corpus$vocab, 25, 0.1, 0.1)

EDAnonymous_top_words <- top.topic.words(EDAnonymous_result$topics, 10, by.score=TRUE)
```

```{r, transgender body}
transgender_body_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_transgender_body_posts.csv")

transgender_body_corpus <- lexicalize(transgender_body_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
transgender_body_result <- lda.collapsed.gibbs.sampler(transgender_body_corpus$documents, K, transgender_body_corpus$vocab, 25, 0.1, 0.1)

transgender_body_top_words <- top.topic.words(transgender_body_result$topics, 10, by.score=TRUE)
```

```{r, transgender dysphori}
transgender_dysphori_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_transgender_dysphori_posts.csv")

transgender_dysphori_corpus <- lexicalize(transgender_dysphori_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
transgender_dysphori_result <- lda.collapsed.gibbs.sampler(transgender_dysphori_corpus$documents, K, transgender_dysphori_corpus$vocab, 25, 0.1, 0.1)

transgender_dysphori_top_words <- top.topic.words(transgender_dysphori_result$topics, 10, by.score=TRUE)
```

```{r, transgender weigh}
transgender_weigh_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_transgender_weigh_posts.csv")

transgender_weigh_corpus <- lexicalize(transgender_weigh_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
transgender_weigh_result <- lda.collapsed.gibbs.sampler(transgender_weigh_corpus$documents, K, transgender_weigh_corpus$vocab, 25, 0.1, 0.1)

transgender_weigh_top_words <- top.topic.words(transgender_weigh_result$topics, 10, by.score=TRUE)
```

```{r, transgender diet}
transgender_diet_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_transgender_diet_posts.csv")

transgender_diet_corpus <- lexicalize(transgender_diet_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
transgender_diet_result <- lda.collapsed.gibbs.sampler(transgender_diet_corpus$documents, K, transgender_diet_corpus$vocab, 25, 0.1, 0.1)

transgender_diet_top_words <- top.topic.words(transgender_diet_result$topics, 10, by.score=TRUE)
```

```{r, asktransgender body}
asktransgender_body_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_asktransgender_body_posts.csv")

asktransgender_body_corpus <- lexicalize(asktransgender_body_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
asktransgender_body_result <- lda.collapsed.gibbs.sampler(asktransgender_body_corpus$documents, K, asktransgender_body_corpus$vocab, 25, 0.1, 0.1)

asktransgender_body_top_words <- top.topic.words(asktransgender_body_result$topics, 10, by.score=TRUE)
```

```{r, asktransgender dysphori}
asktransgender_dysphori_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_asktransgender_dysphori_posts.csv")

asktransgender_dysphori_corpus <- lexicalize(asktransgender_dysphori_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
asktransgender_dysphori_result <- lda.collapsed.gibbs.sampler(asktransgender_dysphori_corpus$documents, K, asktransgender_dysphori_corpus$vocab, 25, 0.1, 0.1)

asktransgender_dysphori_top_words <- top.topic.words(asktransgender_dysphori_result$topics, 10, by.score=TRUE)
```

```{r, asktransgender weigh}
asktransgender_weigh_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_asktransgender_weigh_posts.csv")

asktransgender_weigh_corpus <- lexicalize(asktransgender_weigh_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
asktransgender_weigh_result <- lda.collapsed.gibbs.sampler(asktransgender_weigh_corpus$documents, K, asktransgender_weigh_corpus$vocab, 25, 0.1, 0.1)

asktransgender_weigh_top_words <- top.topic.words(asktransgender_weigh_result$topics, 10, by.score=TRUE)
```

```{r, asktransgender diet}
asktransgender_diet_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_asktransgender_diet_posts.csv")

asktransgender_diet_corpus <- lexicalize(asktransgender_diet_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
asktransgender_diet_result <- lda.collapsed.gibbs.sampler(asktransgender_diet_corpus$documents, K, asktransgender_diet_corpus$vocab, 25, 0.1, 0.1)

asktransgender_diet_top_words <- top.topic.words(asktransgender_diet_result$topics, 10, by.score=TRUE)
```

```{r, genderqueer body}
genderqueer_body_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_genderqueer_body_posts.csv")

genderqueer_body_corpus <- lexicalize(genderqueer_body_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
genderqueer_body_result <- lda.collapsed.gibbs.sampler(genderqueer_body_corpus$documents, K, genderqueer_body_corpus$vocab, 25, 0.1, 0.1)

genderqueer_body_top_words <- top.topic.words(genderqueer_body_result$topics, 10, by.score=TRUE)
```

```{r, genderqueer dysphori}
genderqueer_dysphori_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_genderqueer_dysphori_posts.csv")

genderqueer_dysphori_corpus <- lexicalize(genderqueer_dysphori_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
genderqueer_dysphori_result <- lda.collapsed.gibbs.sampler(genderqueer_dysphori_corpus$documents, K, genderqueer_dysphori_corpus$vocab, 25, 0.1, 0.1)

genderqueer_dysphori_top_words <- top.topic.words(genderqueer_dysphori_result$topics, 10, by.score=TRUE)
```

```{r, genderqueer weigh}
genderqueer_weigh_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_genderqueer_weigh_posts.csv")

genderqueer_weigh_corpus <- lexicalize(genderqueer_weigh_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
genderqueer_weigh_result <- lda.collapsed.gibbs.sampler(genderqueer_weigh_corpus$documents, K, genderqueer_weigh_corpus$vocab, 25, 0.1, 0.1)

genderqueer_weigh_top_words <- top.topic.words(genderqueer_weigh_result$topics, 10, by.score=TRUE)
```

```{r, genderqueer diet}
genderqueer_diet_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_genderqueer_diet_posts.csv")

genderqueer_diet_corpus <- lexicalize(genderqueer_diet_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
genderqueer_diet_result <- lda.collapsed.gibbs.sampler(genderqueer_diet_corpus$documents, K, genderqueer_diet_corpus$vocab, 25, 0.1, 0.1)

genderqueer_diet_top_words <- top.topic.words(genderqueer_diet_result$topics, 10, by.score=TRUE)
```

```{r, NonBinary body}
NonBinary_body_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_NonBinary_body_posts.csv")

NonBinary_body_corpus <- lexicalize(NonBinary_body_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
NonBinary_body_result <- lda.collapsed.gibbs.sampler(NonBinary_body_corpus$documents, K, NonBinary_body_corpus$vocab, 25, 0.1, 0.1)

NonBinary_body_top_words <- top.topic.words(NonBinary_body_result$topics, 10, by.score=TRUE)
```

```{r, NonBinary dysphori}
NonBinary_dysphori_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_NonBinary_dysphori_posts.csv")

NonBinary_dysphori_corpus <- lexicalize(NonBinary_dysphori_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
NonBinary_dysphori_result <- lda.collapsed.gibbs.sampler(NonBinary_dysphori_corpus$documents, K, NonBinary_dysphori_corpus$vocab, 25, 0.1, 0.1)

NonBinary_dysphori_top_words <- top.topic.words(NonBinary_dysphori_result$topics, 10, by.score=TRUE)
```

```{r, NonBinary weigh}
NonBinary_weigh_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_NonBinary_weigh_posts.csv")

NonBinary_weigh_corpus <- lexicalize(NonBinary_weigh_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
NonBinary_weigh_result <- lda.collapsed.gibbs.sampler(NonBinary_weigh_corpus$documents, K, NonBinary_weigh_corpus$vocab, 25, 0.1, 0.1)

NonBinary_weigh_top_words <- top.topic.words(NonBinary_weigh_result$topics, 10, by.score=TRUE)
```

```{r, NonBinary diet}
NonBinary_diet_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_NonBinary_diet_posts.csv")

NonBinary_diet_corpus <- lexicalize(NonBinary_diet_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
NonBinary_diet_result <- lda.collapsed.gibbs.sampler(NonBinary_diet_corpus$documents, K, NonBinary_diet_corpus$vocab, 25, 0.1, 0.1)

NonBinary_diet_top_words <- top.topic.words(NonBinary_diet_result$topics, 10, by.score=TRUE)
```

```{r, transpassing body}
transpassing_body_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_transpassing_body_posts.csv")

transpassing_body_corpus <- lexicalize(transpassing_body_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
transpassing_body_result <- lda.collapsed.gibbs.sampler(transpassing_body_corpus$documents, K, transpassing_body_corpus$vocab, 25, 0.1, 0.1)

transpassing_body_top_words <- top.topic.words(transpassing_body_result$topics, 10, by.score=TRUE)
```

```{r, transpassing dysphori}
transpassing_dysphori_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_transpassing_dysphori_posts.csv")

transpassing_dysphori_corpus <- lexicalize(transpassing_dysphori_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
transpassing_dysphori_result <- lda.collapsed.gibbs.sampler(transpassing_dysphori_corpus$documents, K, transpassing_dysphori_corpus$vocab, 25, 0.1, 0.1)

transpassing_dysphori_top_words <- top.topic.words(transpassing_dysphori_result$topics, 10, by.score=TRUE)
```

```{r, transpassing weigh}
transpassing_weigh_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_transpassing_weigh_posts.csv")

transpassing_weigh_corpus <- lexicalize(transpassing_weigh_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
transpassing_weigh_result <- lda.collapsed.gibbs.sampler(transpassing_weigh_corpus$documents, K, transpassing_weigh_corpus$vocab, 25, 0.1, 0.1)

transpassing_weigh_top_words <- top.topic.words(transpassing_weigh_result$topics, 10, by.score=TRUE)
```

```{r, transpassing diet}
transpassing_diet_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_transpassing_diet_posts.csv")

transpassing_diet_corpus <- lexicalize(transpassing_diet_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
transpassing_diet_result <- lda.collapsed.gibbs.sampler(transpassing_diet_corpus$documents, K, transpassing_diet_corpus$vocab, 25, 0.1, 0.1)

transpassing_diet_top_words <- top.topic.words(transpassing_diet_result$topics, 10, by.score=TRUE)
```

```{r, FTMFitness body}
FTMFitness_body_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_FTMFitness_body_posts.csv")

FTMFitness_body_corpus <- lexicalize(FTMFitness_body_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
FTMFitness_body_result <- lda.collapsed.gibbs.sampler(FTMFitness_body_corpus$documents, K, FTMFitness_body_corpus$vocab, 25, 0.1, 0.1)

FTMFitness_body_top_words <- top.topic.words(FTMFitness_body_result$topics, 10, by.score=TRUE)
```

```{r, FTMFitness dysphori}
FTMFitness_dysphori_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_FTMFitness_dysphori_posts.csv")

FTMFitness_dysphori_corpus <- lexicalize(FTMFitness_dysphori_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
FTMFitness_dysphori_result <- lda.collapsed.gibbs.sampler(FTMFitness_dysphori_corpus$documents, K, FTMFitness_dysphori_corpus$vocab, 25, 0.1, 0.1)

FTMFitness_dysphori_top_words <- top.topic.words(FTMFitness_dysphori_result$topics, 10, by.score=TRUE)
```

```{r, FTMFitness weigh}
FTMFitness_weigh_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_FTMFitness_weigh_posts.csv")

FTMFitness_weigh_corpus <- lexicalize(FTMFitness_weigh_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
FTMFitness_weigh_result <- lda.collapsed.gibbs.sampler(FTMFitness_weigh_corpus$documents, K, FTMFitness_weigh_corpus$vocab, 25, 0.1, 0.1)

FTMFitness_weigh_top_words <- top.topic.words(FTMFitness_weigh_result$topics, 10, by.score=TRUE)
```

```{r, FTMFitness diet}
FTMFitness_diet_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_FTMFitness_diet_posts.csv")

FTMFitness_diet_corpus <- lexicalize(FTMFitness_diet_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
FTMFitness_diet_result <- lda.collapsed.gibbs.sampler(FTMFitness_diet_corpus$documents, K, FTMFitness_diet_corpus$vocab, 25, 0.1, 0.1)

FTMFitness_diet_top_words <- top.topic.words(FTMFitness_diet_result$topics, 10, by.score=TRUE)
```

```{r, EatingDisorders gender}
EatingDisorders_gender_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_EatingDisorders_gender_posts.csv")

EatingDisorders_gender_corpus <- lexicalize(EatingDisorders_gender_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
EatingDisorders_gender_result <- lda.collapsed.gibbs.sampler(EatingDisorders_gender_corpus$documents, K, EatingDisorders_gender_corpus$vocab, 25, 0.1, 0.1)

EatingDisorders_gender_top_words <- top.topic.words(EatingDisorders_gender_result$topics, 10, by.score=TRUE)
```

```{r, EDAnonymous gender}
EDAnonymous_gender_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_EDAnonymous_gender_posts.csv")

EDAnonymous_gender_corpus <- lexicalize(EDAnonymous_gender_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
EDAnonymous_gender_result <- lda.collapsed.gibbs.sampler(EDAnonymous_gender_corpus$documents, K, EDAnonymous_gender_corpus$vocab, 25, 0.1, 0.1)

EDAnonymous_gender_top_words <- top.topic.words(EDAnonymous_gender_result$topics, 10, by.score=TRUE)
```

```{r, EDAnonymous dysphori}
EDAnonymous_dysphori_posts <- read_csv("~/Documents/Trans_ED_Research/processed_posts/processed_EDAnonymous_dysphori_posts.csv")

EDAnonymous_dysphori_corpus <- lexicalize(EDAnonymous_dysphori_posts$Text, lower=TRUE)

K <- 10 ## Num clusters
EDAnonymous_dysphori_result <- lda.collapsed.gibbs.sampler(EDAnonymous_dysphori_corpus$documents, K, EDAnonymous_dysphori_corpus$vocab, 25, 0.1, 0.1)

EDAnonymous_dysphori_top_words <- top.topic.words(EDAnonymous_dysphori_result$topics, 10, by.score=TRUE)
```

```{r, display results}
transgender_top_words
asktransgender_top_words
genderqueer_top_words
NonBinary_top_words
transpassing_top_words
FTMFitness_top_words
EatingDisorders_top_words
EDAnonymous_top_words

```

```{r, display body}
transgender_body_top_words
asktransgender_body_top_words
genderqueer_body_top_words
NonBinary_body_top_words
transpassing_body_top_words
FTMFitness_body_top_words

```
```{r, display dysphoria}
transgender_dysphori_top_words
asktransgender_dysphori_top_words
genderqueer_dysphori_top_words
NonBinary_dysphori_top_words
transpassing_dysphori_top_words
FTMFitness_dysphori_top_words
EDAnonymous_dysphori_top_words
```
```{r, display diet}
transgender_diet_top_words
asktransgender_diet_top_words
genderqueer_diet_top_words
NonBinary_diet_top_words
transpassing_diet_top_words
FTMFitness_diet_top_words
```
```{r, display weight}
transgender_weigh_top_words
asktransgender_weigh_top_words
genderqueer_weigh_top_words
NonBinary_weigh_top_words
transpassing_weigh_top_words
FTMFitness_weigh_top_words
```
```{r, display gender}
EatingDisorders_gender_top_words
EDAnonymous_gender_top_words
```


